---
- name: Vector | Install rpm
  ansible.builtin.dnf:
    disable_gpg_check: true
    name: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm
    state: present
- name: Vector | Config
  ansible.builtin.template:
    src: vector.toml.j2
    mode: "0644"
    dest: /etc/vector/vector.toml
#    validate: vector validate --no-environment --config-yaml %s
- name: Vector | Create systemd unit
  ansible.builtin.template:
    src: vector.service.j2
    mode: "0644"
    dest: /etc/systemd/system/vector.service
  notify: Restart vector service
