---
role_name_check: 1
driver:
  name: docker
platforms:
#  - name: centos8
#    image: quay.io/centos/centos:stream8
#    pre_build_image: true
  - name: fedora
    image: pycontribs/fedora
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible