---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: fedora
    image: docker.io/pycontribs/fedora:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
